nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'https://www.example.com']
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        expose_headers: []
        max_age: 7200
        allow_credentials: true
    paths:
        '^/api/': ~
